"""Add graph models and pgvector

Revision ID: 5dc51aa46843
Revises: 001
Create Date: 2026-07-14 16:46:48.024407+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dc51aa46843'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('projected_victims', sa.Integer(), nullable=True),
    sa.Column('takedown_brief', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PHONE', 'UPI', 'EMAIL', 'URL', 'HANDLE', 'AADHAAR', 'PAN', 'IFSC', 'ACCOUNT', 'NAME', name='entitytype', native_enum=False), nullable=False),
    sa.Column('value_hash', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_value_hash'), 'entities', ['value_hash'], unique=False)
    op.create_table('case_entity_links',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'entity_id')
    )
    op.create_table('semantic_links',
    sa.Column('a_id', sa.UUID(), nullable=False),
    sa.Column('b_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['a_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['b_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('a_id', 'b_id')
    )
    op.add_column('cases', sa.Column('fraud_type', sa.Enum('digital_arrest', 'job_fraud', 'investment_fraud', 'customer_support', 'sextortion', 'ecommerce', 'other', name='fraudtype', native_enum=False), nullable=True))
    op.add_column('cases', sa.Column('risk', sa.Enum('danger', 'suspicious', 'likely_safe', 'unknown', name='risklevel', native_enum=False), nullable=True))
    op.add_column('cases', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('cases', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('cases', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.add_column('cases', sa.Column('language', sa.String(), nullable=True))
    op.alter_column('cases', 'status',
               existing_type=postgresql.ENUM('queued', 'classifying', 'extracting', 'linking', 'clustered', 'needs_manual_review', 'failed', name='case_status'),
               type_=sa.Enum('queued', 'classifying', 'extracting', 'linking', 'clustered', 'needs_manual_review', 'failed', name='casestatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::case_status"))
    op.alter_column('cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'cases', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('uq_pii_vault_token'), 'pii_vault', type_='unique')
    op.drop_index(op.f('ix_pii_vault_token'), table_name='pii_vault')
    op.create_index(op.f('ix_pii_vault_token'), 'pii_vault', ['token'], unique=True)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_pii_vault_token'), table_name='pii_vault')
    op.create_index(op.f('ix_pii_vault_token'), 'pii_vault', ['token'], unique=False)
    op.create_unique_constraint(op.f('uq_pii_vault_token'), 'pii_vault', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.alter_column('cases', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cases', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cases', 'status',
               existing_type=sa.Enum('queued', 'classifying', 'extracting', 'linking', 'clustered', 'needs_manual_review', 'failed', name='casestatus', native_enum=False),
               type_=postgresql.ENUM('queued', 'classifying', 'extracting', 'linking', 'clustered', 'needs_manual_review', 'failed', name='case_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::case_status"))
    op.drop_column('cases', 'language')
    op.drop_column('cases', 'campaign_id')
    op.drop_column('cases', 'embedding')
    op.drop_column('cases', 'confidence')
    op.drop_column('cases', 'risk')
    op.drop_column('cases', 'fraud_type')
    op.drop_table('semantic_links')
    op.drop_table('case_entity_links')
    op.drop_index(op.f('ix_entities_value_hash'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
